# build.ps1 - build HagVampire.dll and deploy it as a normal Mod Organizer 2 mod.
[CmdletBinding()]
param(
    [switch]$NoBuild,
    [string]$Mo2Mods = 'C:\Users\Yannis\AppData\Local\ModOrganizer\Skyrim Special Edition\mods'
)
$ErrorActionPreference = 'Stop'
$root  = $PSScriptRoot
$cmake = 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe'
$papyrusCompiler = 'C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Papyrus Compiler\PapyrusCompiler.exe'
$scriptsZip = 'C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Scripts.zip'
$vanillaSource = Join-Path $root 'build\PapyrusSource'
$papyrusImports  = @(
    (Join-Path $root 'papyrus\Source'),
    (Join-Path $root 'papyrus\Stubs'),
    $vanillaSource
) -join ';'
$papyrusOut = Join-Path $root 'assets\Scripts'

function Enable-MO2PluginForEnabledMod {
    param(
        [string]$Mo2ModsPath,
        [string]$ModName,
        [string]$PluginName
    )

    $mo2Root = Split-Path $Mo2ModsPath -Parent
    $profiles = Join-Path $mo2Root 'profiles'
    if (-not (Test-Path $profiles)) { return }

    Get-ChildItem $profiles -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        $modlist = Join-Path $_.FullName 'modlist.txt'
        if (Test-Path $modlist) {
            $modLines = Get-Content $modlist
            if ($modLines -contains "+$ModName") {
                $plugins = Join-Path $_.FullName 'plugins.txt'
                $pluginLines = @()
                if (Test-Path $plugins) {
                    $pluginLines = @(Get-Content $plugins | Where-Object {
                        $_ -notmatch "^\*?$([regex]::Escape($PluginName))$"
                    })
                } else {
                    $pluginLines = @('# This file was automatically generated by Mod Organizer.')
                }
                $pluginLines += "*$PluginName"
                Set-Content -Path $plugins -Value $pluginLines -Encoding UTF8

                $loadorder = Join-Path $_.FullName 'loadorder.txt'
                $loadLines = @()
                if (Test-Path $loadorder) {
                    $loadLines = @(Get-Content $loadorder)
                }
                if (-not ($loadLines -contains $PluginName)) {
                    $loadLines += $PluginName
                    Set-Content -Path $loadorder -Value $loadLines -Encoding UTF8
                }

                Write-Host "enabled $PluginName in MO2 profile '$($_.Name)'"
            }
        }
    }
}

function Ensure-VanillaPapyrusSource {
    if (Test-Path (Join-Path $vanillaSource 'Game.psc')) { return }
    if (-not (Test-Path $scriptsZip)) { throw "Scripts.zip not found: $scriptsZip" }

    New-Item -ItemType Directory -Force $vanillaSource | Out-Null
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead($scriptsZip)
    try {
        foreach ($entry in $archive.Entries) {
            if (-not $entry.FullName.StartsWith('Source/Scripts/')) { continue }
            if (-not $entry.FullName.EndsWith('.psc')) { continue }
            $name = [System.IO.Path]::GetFileName($entry.FullName)
            if (-not $name) { continue }
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile(
                $entry, (Join-Path $vanillaSource $name), $true)
        }
    } finally {
        $archive.Dispose()
    }
}

$espGenerator = Join-Path $root 'tools\make_hagvampire_esp.cjs'
if (Test-Path $espGenerator) {
    Write-Host '== plugin records =='
    & node $espGenerator
    if ($LASTEXITCODE -ne 0) { throw "HagVampire.esp generation failed (exit $LASTEXITCODE)" }
}

if (-not $NoBuild) {
    Set-Location $root
    $env:VCPKG_ROOT = 'C:\dev\vcpkg'
    Write-Host '== configure =='
    & $cmake --preset vs2022 | Select-Object -Last 2
    Write-Host '== build =='
    & $cmake --build "$root\build" --config Release | Select-Object -Last 4
    if ($LASTEXITCODE -ne 0) { throw "build failed (exit $LASTEXITCODE)" }

    if (Test-Path $papyrusCompiler) {
        New-Item -ItemType Directory -Force $papyrusOut | Out-Null
        Ensure-VanillaPapyrusSource
        Write-Host '== papyrus =='
        & $papyrusCompiler (Join-Path $root 'papyrus\Source\HagVampireBridge.psc') "-import=$papyrusImports" "-flags=$(Join-Path $root 'papyrus\TESV_Papyrus_Flags.flg')" "-output=$papyrusOut" -quiet
        if ($LASTEXITCODE -ne 0) { throw "papyrus compile failed (exit $LASTEXITCODE)" }
    } else {
        throw "Papyrus compiler not found: $papyrusCompiler"
    }
}

$dll = Get-ChildItem "$root\build" -Recurse -Filter HagVampire.dll -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $dll) { throw 'HagVampire.dll not found - build first (omit -NoBuild).' }

$mod     = Join-Path $Mo2Mods 'HagVampire'
$plugins = Join-Path $mod 'SKSE\Plugins'
$scripts = Join-Path $mod 'Scripts'
New-Item -ItemType Directory -Force $plugins, $scripts | Out-Null
Copy-Item $dll.FullName (Join-Path $plugins 'HagVampire.dll') -Force
Write-Host "deployed HagVampire.dll -> $plugins"
Copy-Item (Join-Path $papyrusOut 'HagVampireBridge.pex') (Join-Path $scripts 'HagVampireBridge.pex') -Force
Write-Host "deployed HagVampireBridge.pex -> $scripts"

$esp = Join-Path $root 'assets\HagVampire.esp'
if (-not (Test-Path $esp)) { throw "HagVampire.esp not found: $esp" }
Copy-Item $esp (Join-Path $mod 'HagVampire.esp') -Force
Write-Host "deployed HagVampire.esp -> $mod"
Enable-MO2PluginForEnabledMod -Mo2ModsPath $Mo2Mods -ModName 'HagVampire' -PluginName 'HagVampire.esp'

$meta = Join-Path $mod 'meta.ini'
if (-not (Test-Path $meta)) {
    @('[General]', 'gameName=Skyrim Special Edition', 'modid=0', 'version=0.1.0') |
        Set-Content $meta -Encoding UTF8
}

Write-Host "`nMO2 mod ready: $mod"
Get-ChildItem $mod -Recurse -File | ForEach-Object { '  ' + $_.FullName.Substring($mod.Length + 1) }

$commit = Join-Path (Split-Path (Split-Path $root -Parent) -Parent) 'scripts\auto-git-commit.cjs'
if (Test-Path $commit) {
    & node $commit
    if ($LASTEXITCODE -ne 0) { throw "auto commit/push failed (exit $LASTEXITCODE)" }
}
