# build_mods.ps1 - build every external HagLoader mod under mods/ and deploy each DLL as a normal
# Mod Organizer 2 mod:
#   <MO2 mods>\<ModName>\SKSE\Plugins\<ModName>.dll
#
#   .\build_mods.ps1                # build + deploy all mods
#   .\build_mods.ps1 -Only HagGeneral
[CmdletBinding()]
param(
    [string]$Mo2Mods = 'C:\Users\Yannis\AppData\Local\ModOrganizer\Skyrim Special Edition\mods',
    [string]$Only
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$repoRoot = Split-Path $root -Parent
$cmake = 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe'

function Enable-MO2PluginForEnabledMod {
    param(
        [string]$Mo2ModsPath,
        [string]$ModName,
        [string]$PluginName
    )

    $mo2Root = Split-Path $Mo2ModsPath -Parent
    $profiles = Join-Path $mo2Root 'profiles'
    if (-not (Test-Path $profiles)) { return }

    Get-ChildItem $profiles -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        $modlist = Join-Path $_.FullName 'modlist.txt'
        if (Test-Path $modlist) {
            $modLines = Get-Content $modlist
            if ($modLines -contains "+$ModName") {
                $plugins = Join-Path $_.FullName 'plugins.txt'
                $pluginLines = @()
                if (Test-Path $plugins) {
                    $pluginLines = @(Get-Content $plugins | Where-Object {
                        $_ -notmatch "^\*?$([regex]::Escape($PluginName))$"
                    })
                } else {
                    $pluginLines = @('# This file was automatically generated by Mod Organizer.')
                }
                $pluginLines += "*$PluginName"
                Set-Content -Path $plugins -Value $pluginLines -Encoding UTF8

                $loadorder = Join-Path $_.FullName 'loadorder.txt'
                $loadLines = @()
                if (Test-Path $loadorder) {
                    $loadLines = @(Get-Content $loadorder)
                }
                if (-not ($loadLines -contains $PluginName)) {
                    $loadLines += $PluginName
                    Set-Content -Path $loadorder -Value $loadLines -Encoding UTF8
                }

                Write-Host "enabled $PluginName in MO2 profile '$($_.Name)'"
            }
        }
    }
}

$dirs = Get-ChildItem $root -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'CMakeLists.txt') }
if ($Only) { $dirs = $dirs | Where-Object { $_.Name -eq $Only } }
if (-not $dirs) { throw "no mods found under $root (need a subfolder with CMakeLists.txt)" }

foreach ($d in $dirs) {
    $name = $d.Name
    $bld = Join-Path $d.FullName 'build'
    Write-Host "== building mod: $name =="
    & $cmake --preset vs2022 -S $d.FullName | Select-Object -Last 2
    if ($LASTEXITCODE -ne 0) { throw "configure failed for $name" }
    & $cmake --build $bld --config Release | Select-Object -Last 3
    if ($LASTEXITCODE -ne 0) { throw "build failed for $name" }

    $espGenerator = Join-Path $d.FullName 'tools\make_hagvampire_esp.cjs'
    if (Test-Path $espGenerator) {
        Write-Host "== generating plugin records: $name =="
        & node $espGenerator
        if ($LASTEXITCODE -ne 0) { throw "plugin record generation failed for $name" }
    }

    $dll = Get-ChildItem $bld -Recurse -Filter "$name.dll" -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $dll) { $dll = Get-ChildItem $bld -Recurse -Filter '*.dll' | Select-Object -First 1 }
    if (-not $dll) { throw "no DLL produced for $name" }

    $modOut = Join-Path $Mo2Mods $name
    $pluginsOut = Join-Path $modOut 'SKSE\Plugins'
    New-Item -ItemType Directory -Force $pluginsOut | Out-Null

    [System.IO.File]::Copy($dll.FullName, (Join-Path $pluginsOut $dll.Name), $true)
    Write-Host "deployed $($dll.Name) -> $pluginsOut"

    if ($name -eq 'HagGeneral') {
        $oldIni = Join-Path $pluginsOut 'HagGeneral.ini'
        if (Test-Path $oldIni) {
            Remove-Item -LiteralPath $oldIni -Force
            Write-Host "removed old HagGeneral.ini from $pluginsOut"
        }
    }

    Get-ChildItem (Join-Path $d.FullName 'assets') -File -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.Extension -in @('.esp', '.esm', '.esl')) {
            [System.IO.File]::Copy($_.FullName, (Join-Path $modOut $_.Name), $true)
            Write-Host "deployed $($_.Name) -> $modOut"
            Enable-MO2PluginForEnabledMod -Mo2ModsPath $Mo2Mods -ModName $name -PluginName $_.Name
        } else {
            [System.IO.File]::Copy($_.FullName, (Join-Path $pluginsOut $_.Name), $true)
            Write-Host "deployed $($_.Name) -> $pluginsOut"
        }
    }

    Get-ChildItem (Join-Path $d.FullName 'assets') -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $modOut $_.Name) -Recurse -Force
        Write-Host "deployed asset folder $($_.Name) -> $modOut"
    }

    $meta = Join-Path $modOut 'meta.ini'
    if (-not (Test-Path $meta)) {
        @('[General]', 'gameName=Skyrim Special Edition', 'modid=0', 'version=0.1.0') |
            Set-Content $meta -Encoding UTF8
    }
}

Write-Host "`nAll external mods built + deployed under $Mo2Mods"

$commit = Join-Path $repoRoot 'scripts\auto-git-commit.cjs'
if (Test-Path $commit) {
    & node $commit
    if ($LASTEXITCODE -ne 0) { throw "auto commit/push failed (exit $LASTEXITCODE)" }
}
